apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: culmv90sc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: culmv90sc-nodejs 
  name: culmv90sc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: culmv90sc-nodejs 
